### ISSUE TITLE
打开言灵集开关爆红后无法关闭，并且使用一次言灵后左侧也爆红。

### ISSUE THREAD

**Issue by KiraBoXin** [chris81605/Degrees-of-Lewdity_Cheat_Extended#2]
[1.txt](https://github.com/chris81605/Degrees-of-Lewdity_Cheat_Extended/files/15005026/1.txt)
附存档文件

**Comment by chris81605** [comment]
經測試無問題
* 建議嘗試使用DEBUG MODE
開關在`選項=>模組設置`

**Comment by liii-a** [comment]
老师，我开了debug也点了修复，还是这样😭

![Image](https://github.com/user-attachments/assets/0ab540e4-aaea-47aa-aa37-2697b7dd7799)
![Image](https://github.com/user-attachments/assets/1789a18b-74f1-4527-9591-772827a33da0)
![Image](https://github.com/user-attachments/assets/298dffc7-5ad2-44c1-bca9-e351a2fdd885)

**Comment by chris81605** [comment]
換成maplebirch 框架呢？
