### ISSUE TITLE
只显示一键烘干功能

### ISSUE THREAD

**Issue by HSSkyBoy** [chris81605/Degrees-of-Lewdity_Cheat_Extended#3]
游戏版本 0.5.0.5 
汉化版本 1.0.0alpha
CE版本 1.15

设置的模组界面只有一个功能
![Screenshot_20240615_134111_com.vrelnir.DegreesOfLewdity.Mod.jpg](https://github.com/chris81605/Degrees-of-Lewdity_Cheat_Extended/assets/122550437/3e0df65d-311b-484b-988f-189e7d42796c)

**Comment by chris81605** [comment]
經測試未發現問題，建議嘗試使用最新版簡易框架

**Comment by chris81605** [comment]
Close
